import { Inter,Signika,Dangrek,Revalia,Ubuntu_Mono,Trispace,Martian_Mono,JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer/Footer'
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const signika = Signika({subsets:['latin'],weight:'400'});
const dangrek = Dangrek({subsets:['latin'],weight:'400'});
const revalia = Revalia({subsets:['latin'],weight:['400']});
const ubuntu = Ubuntu_Mono({subsets:['latin'],weight:['700']});
const trispace = Trispace({subsets:['latin'],weight:['500']});
const martian_Mono = Martian_Mono({subsets:['latin'],weight:['400']});
const jetBrains_Mono = JetBrains_Mono({subsets:['latin'],weight:['400']});

export const metadata = {
  title: "Synwave",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <Head>
      <link rel="apple-touch-icon" sizes="180x180" href="/icon.ico"/>
<link rel="icon" type="image/png" sizes="32x32" href="/icon.ico"/>
<link rel="icon" type="image/png" sizes="16x16" href="/icon.ico"/>
<link rel="manifest" href="/icon.ico"/>
<link rel="mask-icon" href="/icon.ico" color="#5bbad5"/>
<meta name="msapplication-TileColor" content="#da532c"/>
<meta name="theme-color" content="#ffffff"/>
      </Head>

      <body className={`${signika.className} min-h-screen flex flex-col`}>
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

